# Use postgres/example user/password credentials

services:

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: administrador
      POSTGRES_DB: gestionjwt
    ports:
      - "0.0.0.0:5432:5432"
  adminer:
    container_name: adminer_ui
    image: adminer
    restart: always
    ports:
      - "0.0.0.0:8081:8080"
